# Workflow for testing our code regularly
name: CI for Notion applications

# Controls when the action will run.
on:
  push:
    # Only run if these paths change.
    paths:
      - notion/**
      - workers/**
      - utils/**
    # Only run on the main branch.
    branches: [main]
  pull_request:
    # Only run if these paths change.
    paths:
      - ".github/workflows/ci.yml"
      - notion/**
      - workers/**
      - utils/**
    # Only run on the main branch.
    branches: [main]

jobs:
  uses: szenius/set-timezone@v1.0
    with:
      timezoneLinux: "America/New York"
  # Test our various workers.
  test_workers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.0"

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Install python dev packages
        run: pipenv install -d

      - name: Run ci
        run: pipenv run python ci_helper.py
