name: handle-recurring-tasks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # runs at 00:00 UTC (8pm EST) everyday
    - cron: "0 12 * * *" # runs at 12:00 UTC (8am EST) everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.0"

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: install python packages
        run: pipenv install

      - name: execute Python script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_TASKS_DB_ID: ${{ secrets.NOTION_TASKS_DB_ID }}
          NOTION_EXECUTIONS_DB_ID: ${{ secrets.NOTION_EXECUTIONS_DB_ID }}
        run: pipenv run python cli.py

      # - name: commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git commit -m "update execution" -a
      #     git push
